"""в Users добавлена колонка city_from

Revision ID: 160f00820caa
Revises: 
Create Date: 2022-03-30 17:42:38.871370

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '160f00820caa'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('city_from', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'city_from')
    # ### end Alembic commands ###
