"""добавлена таблица Category и промежуточная jobs_to_category

Revision ID: db19765dfe7d
Revises: 160f00820caa
Create Date: 2022-03-30 18:39:33.772709

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'db19765dfe7d'
down_revision = '160f00820caa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('jobs_to_category',
    sa.Column('jobs', sa.Integer(), nullable=True),
    sa.Column('category', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['category'], ['category.id'], ),
    sa.ForeignKeyConstraint(['jobs'], ['jobs.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('jobs_to_category')
    op.drop_table('category')
    # ### end Alembic commands ###
